# -*- coding: utf-8 -*-
"""dbt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-H4OGCBvO-HecAhk6tgkP3jb5mLhFZh
"""

from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2024, 12, 10),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(
    'bitcoin_dbt_pipeline',
    default_args=default_args,
    description='DAG for running dbt models, tests, and snapshots for Bitcoin data',
    schedule_interval='@daily',
    catchup=False
)

# Task 1: dbt run
dbt_run = BashOperator(
    task_id='dbt_run',
    bash_command='cd /opt/airflow/dw_project && source ~/.dbt/env && dbt run --profiles-dir .',
    dag=dag
)

# Task 2: dbt test
dbt_test = BashOperator(
    task_id='dbt_test',
    bash_command='cd /opt/airflow/dw_project && source ~/.dbt/env && dbt test --profiles-dir .',
    dag=dag
)

# Task 3: dbt snapshot
dbt_snapshot = BashOperator(
    task_id='dbt_snapshot',
    bash_command='cd /opt/airflow/dw_project && source ~/.dbt/env && dbt snapshot --profiles-dir .',
    dag=dag
)

# Set task dependencies
dbt_run >> dbt_test >> dbt_snapshot